[package]
name = "satellisation"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json", "tls"] }
rocket_dyn_templates = { version = "0.2.0", features = ["tera"] }
ws = { package = "rocket_ws", version = "0.1.1" }
